### PR TITLE
fixed index leaking and get/index for id:0 w/ tests

### PR DESCRIPTION
**Pull request by flipside**
Tracked down a bug that was causing models with an attribute value of 0 to not be indexed or accessible with `get(0)`. 

Also found that indexes were leaking into the root `this.index` when not overwritten so fixed that too.

### CODE REVIEW

**Comment by flipside** [comment]
i've got another bug fix for when the collection has a mainIndex that's different from the model idAttribute, should i add it to this PR or make a separate PR?

**Comment by kamilogorek** [comment]
+1

**Comment by bear** [comment]
@flipside let's get this PR merged, so please add a new PR for the second case you referenced

**Comment by kamilogorek** [comment]
@bear It has been already added :)

**Comment by bear** [comment]
oh! sorry, that is one problem with me not being an active user of this code - I tend to miss bits here and there

**Comment by flipside** [comment]
@bear 3 bug fixes in here, merge away!

**Comment by HenrikJoreteg** [comment]
thanks all, @flipside especially. Sorry for the delay. Published as `1.4.2`

**Comment by flipside** [comment]
sweet, happy to help. :grinning:

**Pull request merged**
