### PR TITLE
update testing framework, fix isCollection bug

### PR DESCRIPTION
**Pull request by wraithgar**
Switch fully to zuul
Add saucelabs config
Use node LTS and npm 2 for building

See discussion that led to this here: AmpersandJS/ampersand-filtered-subcollection#26

Setting isCollection as a `value` property meant that
some browsers (phantomjs at least) were allowing it to be
overwritten. Changed to a proper getter only.

This will warrant a new release, unlike most of the other PRs that are updating testing, as there was a change in the code itself.

### CODE REVIEW

**Comment by kamilogorek** [comment]
:ok_hand:

**Comment by wraithgar** [comment]
travis is having issues today btw, will wait till things are better to re-start tests.

**Comment by kamilogorek** [comment]
@wraithgar could you rerun tests on Travis? It looks like it stuck

**Comment by lukekarrys** [comment]
+1

**Comment by wraithgar** [comment]
Published as `v1.5.1`

**Pull request merged**
