### PR TITLE
feature: permit indexing on derived

### PR DESCRIPTION
**Pull request by cdaringe**
# problem statement
i want to index on a derived attribute. i am unable to in the current state.  i have a justifiable case where my datasource cannot provide a reliably unique ID, but I can compute one from the composite data object.

# solution
- detect if `mainIndex` is part of the derived definition as a last check when assigning the key
- if found, compute the derived id
- proceed as normal!

### CODE REVIEW

**Comment by lukekarrys** [comment]
+1 (pending travis check passing)

**Comment by cdaringe** [comment]
@wraithgar, you spent your fair share in collection-town.  May I have a review from you as well?

**Comment by cdaringe** [comment]
Friendly bump!

**Comment by wraithgar** [comment]
This is a good idea which in hindsight seems like a no-brainer that should already exist.

Just so I'm following along, the use case here is for when a non-ampersand-state object is passed in, and the index is a derived property.  This means we have to apply the derived function from the model's prototype onto the attributes in order to figure out what the result of that attribute is, and is why we can't just go `lodash.result` because it's not an instantiated ampersand-state object.

The only place this would seem to be able to fall over is when you have nested derived properties, i.e. a property that is derived from another derived property.

**Comment by cdaringe** [comment]
> Just so I'm following along, the use case here is for when a non-ampersand-state object is passed in, and the index is a derived property.

Yup!

>  apply the derived function from the model's prototype onto the attributes in order to figure out what the result of that attribute is, and is why we can't just go lodash.result because it's not an instantiated ampersand-state object.

Double yup!

> ... to fall over is when you have nested derived properties, i.e. a property that is derived from another derived property.

triple, flipping, yup.

any other follow up on it? :)

**Comment by wraithgar** [comment]
+1 I think supporting this in most cases is better than none.

**Comment by cdaringe** [comment]
cool!  i'll release 1.5.0 soon if someone would be willing to grant publish access

**Comment by lukekarrys** [comment]
@cdaringe done! :+1:

**Pull request merged**
