### PR TITLE
Fix deopt caused by nonlocal forIn in indices

### PR DESCRIPTION
**Pull request by STRML**
Noticed this sucking up a good amount of time in profiling; easy fix so why not throw it in.

For reference:

https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#5-for-in

screen shot 2016-01-05 at 6 15 06 pm

### CODE REVIEW

**Comment by wraithgar** [comment]
+1 nice quick patch

**Comment by kamilogorek** [comment]
Sweet! :+1: 

@STRML where I can read about benchmarking syntax you're using here? eg. `%OptimizeFunctionOnNextCall` and `%GetOptimizationStatus`?

**Comment by STRML** [comment]
@kamilogorek https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#1-tooling is the bible!

**Comment by kamilogorek** [comment]
@STRML Perfect, thanks!

**Comment by wraithgar** [comment]
published as `v1.6.0`

**Pull request merged**
